<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotReview.Application\DotReview.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Prompts\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
